function Reset_R_TD = Reset_R(in1)
%RESET_R
%    RESET_R_TD = RESET_R(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Feb-2018 14:47:43

Y2 = in1(1,:);
Y3 = in1(2,:);
Y4 = in1(3,:);
Y5 = in1(4,:);
Y6 = in1(5,:);
Y7 = in1(6,:);
Y8 = in1(7,:);
Y9 = in1(8,:);
t2 = sin(Y5);
t3 = Y9.*2.0;
t4 = Y5.*2.0;
t5 = t3+t4;
Reset_R_TD = [Y2;Y3;Y4;Y5;Y6;Y7;Y8;Y9;-(Y2+Y3.*Y6.*2.0+Y6.*t2.*(1.0./2.0)+Y6.*sin(Y5+t3).*(1.0./2.0)+Y2.*cos(t5)+Y4.*sin(t5))./(Y3.*2.0+t2)];
