function Guard_R_TD = Guard_R(in1)
%GUARD_R
%    GUARD_R_TD = GUARD_R(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Sep-2018 17:19:07

Y3 = in1(3,:);
Y5 = in1(5,:);
Y9 = in1(9,:);
Guard_R_TD = Y3-cos(Y5+Y9)+sin(Y5).*(1.0./2.0);
