function Guard_L_TD = Guard_L(in1)
%GUARD_L
%    GUARD_L_TD = GUARD_L(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Sep-2018 17:19:07

Y3 = in1(3,:);
Y5 = in1(5,:);
Y7 = in1(7,:);
Guard_L_TD = Y3-cos(Y5+Y7)-sin(Y5).*(1.0./2.0);
