function g00_poly = FF_Dyn_poly_g(in1)
%FF_DYN_POLY_G
%    G00_POLY = FF_DYN_POLY_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Sep-2018 22:38:32

g00_poly = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[10,2]);
