function Guard_R_TD = Guard_R(in1)
%GUARD_R
%    GUARD_R_TD = GUARD_R(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Feb-2018 14:47:43

Y3 = in1(2,:);
Y5 = in1(4,:);
Y9 = in1(8,:);
Guard_R_TD = Y3-cos(Y5+Y9)+sin(Y5).*(1.0./2.0);
